fullnameOverride: "kafka"

# Enable Zookeeper
zookeeper:
  enabled: true

# Bitnami Kafka configuration
kafka:
  brokerId: 1
  zookeeperConnect: "zookeeper:2181"
  
  # Simple listeners for internal cluster communication
  listenerSecurityProtocolMap: "PLAINTEXT:PLAINTEXT"
  advertisedListeners: "PLAINTEXT://kafka:9092"
  
  # Topic Configuration
  offsetsTopicReplicationFactor: 1
  groupInitialRebalanceDelayMs: 0
  
  # Performance Tuning
  messageMaxBytes: "5242880"
  replicaFetchMaxBytes: "5242880"

# Use Bitnami image instead of Confluent
image:
  repository: bitnami/kafka
  tag: "3.4.1"
  pullPolicy: IfNotPresent

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Disable persistence for now
persistence:
  enabled: false

# Security context for Bitnami
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
