fullnameOverride: "minio"

url:
  hostname: "minio-ilifu.openup.org.za"

console:
  url:
    hostname: "minio-console-ilifu.openup.org.za"
  ingress:
    enabled: true
    className: "private"
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    tls: []

image:
  repository: minio/minio
  tag: "RELEASE.2024-01-16T16-07-38Z"

minio:
  accessKey: admin
  secretKey: admin123
  
  buckets:
    - name: state
    - name: object
  
  bucketSetup:
    enabled: true

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 128Mi

persistence:
  enabled: true
  size: 5Gi

probes:
  liveness:
    enabled: true 
    httpGet:
      path: /minio/health/live
      port: api
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    enabled: true
    httpGet:
      path: /minio/health/ready
      port: api
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

ingress:
  enabled: true
  className: "private"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  hosts:
    - host: minio-ilifu.openup.org.za
      paths:
        - path: /
          pathType: Prefix
