fullnameOverride: "song"

url:
  hostname: "song-ilifu.openup.org.za"

image:
  repository: ghcr.io/overture-stack/song-server
  tag: "5.0.2"

song:
  spring:
    profiles:
      active: "prod,secure,kafka"
    flyway:
      enabled: true
  
  # Song Variables
  id:
    useLocal: true
  schemas:
    enforceLatest: true
  
  # Score Variables
  score:
    url: "http://score:8087"
    accessToken: ""
  
  auth:
    server:
      provider: "keycloak"
      clientId: "dms"
      clientSecret: "some-secret-value"
      tokenName: "apiKey"
      keycloak:
        host: "http://keycloak:8080"
        realm: "myrealm"
      scope:
        study:
          prefix: "STUDY."
          suffix: ".WRITE"
        system: "song.WRITE"
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: "http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs"
      introspectionUri: "http://keycloak:8080/realms/myrealm/apikey/check_api_key/"
  
  # Database Variables 
  datasource:
    url: "jdbc:postgresql://song-db:5432/songDb?stringtype=unspecified"
    username: "admin"
    password: "song-db-pass-123"
  
  # Kafka Variables
  kafka:
    bootstrapServers: "kafka.agari.svc.cluster.local:9092"
    template:
      defaultTopic: "song-analysis"
  
  # Swagger Variable
  swagger:
    alternateUrl: "/swagger-api"

resources:
  limits:
    cpu: 500m     
    memory: 1.5Gi  
  requests:
    cpu: 150m      
    memory: 768Mi  

# Probe configuration
probes:
  liveness:
    enabled: false 
    httpGet:
      path: /actuator/health
      port: 8081
    initialDelaySeconds: 300  
    periodSeconds: 60         
    timeoutSeconds: 10
    failureThreshold: 5       
  
  readiness:
    enabled: true
    tcpSocket:
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

ingress:
  enabled: true
  className: "private"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: song-ilifu.openup.org.za
      paths:
        - path: /
          pathType: Prefix
