# Bitnami Kafka Configuration for Development
# Use this instead of the custom Kafka chart

# Disable persistence for development
persistence:
  enabled: false

# Zookeeper settings
zookeeper:
  persistence:
    enabled: false

# Controller and Broker settings
controller:
  replicaCount: 1

broker:
  replicaCount: 1

# Authentication settings (plaintext for development)
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false
    mechanism: plain
  tls:
    enabled: false

# Listeners configuration
listeners:
  client:
    protocol: plaintext
  interbroker:
    protocol: plaintext

# Security settings
sasl:
  enabled: false
  mechanism: plain
  
tls:
  enabled: false

# Service configuration
service:
  type: ClusterIP
  port: 9092

# Resource limits for development
controller:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

broker:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
