fullnameOverride: "song-db"

postgresql:
  postgresqlUsername: admin
  postgresqlPassword: song-db-pass-123
  postgresqlDatabase: songDb

persistence:
  size: 2Gi

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
