replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "14"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 999

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  # storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: ""

postgresql:
  postgresqlUsername: admin
  postgresqlPassword: admin123
  postgresqlDatabase: keycloakDb

databaseKey: ""  # e.g., "keycloak", "song"

probes:
  liveness:
    enabled: true
    exec:
      command:
        - /bin/sh
        - -c
        - exec pg_isready -U "$(POSTGRES_USER)" -d "$(POSTGRES_DB)" -h 127.0.0.1 -p 5432
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
  
  readiness:
    enabled: true
    exec:
      command:
        - /bin/sh
        - -c
        - -e
        - |
          exec pg_isready -U "$(POSTGRES_USER)" -d "$(POSTGRES_DB)" -h 127.0.0.1 -p 5432
          [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
