apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride | default (printf "%s-postgres" .Release.Name) }}-init-scripts
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "postgres" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  init.sql: |
{{ .Files.Get "sql/init.sql" | indent 4 }}
