apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (printf "%s-postgres" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "postgres" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
