# AGARI Overture Stack - Essential Workflow
# Test file info
@test_file_name = test_data.fasta
@test_file_size = 298
@test_file_md5 = cc70b8e811b39c98a938edf87145e34d

# Fixed IDs for Keycloak permissions
@study_id = study1
@analysis_id = analysis001

# Authentication config
@username = admin
@password = password123
@realm = agari
@client_id = dms
@client_secret = dms-secret

### 1. LOGIN to get access token
# @name login
POST http://keycloak.local/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username={{username}}
&password={{password}}
&grant_type=password
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@token = {{login.response.body.access_token}}

### 2. GET UMA TOKEN (RPT) for resource access
# @name rptToken
POST http://keycloak.local/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:uma-ticket
&client_id={{client_id}}
&client_secret={{client_secret}}
&audience={{client_id}}
&subject_token={{token}}
&subject_token_type=urn:ietf:params:oauth:token-type:access_token

###
@rpt_token = {{rptToken.response.body.access_token}}

### 3. CREATE STUDY
POST http://song.local/studies/{{study_id}}/
Authorization: Bearer {{rpt_token}}
Content-Type: application/json

{
  "studyId": "{{study_id}}",
  "name": "AGARI Test Study", 
  "description": "Test study for genomic data workflow",
  "organization": "NICD",
  "info": {
    "projectType": "genomics",
    "region": "South Africa"
  }
}

### 4. SUBMIT ANALYSIS
# @name submitAnalysis
POST http://song.local/submit/{{study_id}}/
Authorization: Bearer {{rpt_token}}
Content-Type: application/json

< ./data/analysis_submission.json

### 5. GET ANALYSIS DETAILS
# Extract analysis_id from step 4 response and get full analysis details
@submitted_analysis_id = {{submitAnalysis.response.body.analysisId}}
# @name getAnalysis
GET http://song.local/studies/{{study_id}}/analysis/{{submitted_analysis_id}}
Authorization: Bearer {{rpt_token}}

### 6. INITIALIZE SCORE UPLOAD
# Extract object_id from step 5 response
@object_id = {{getAnalysis.response.body.files[0].objectId}}
# @name initUpload
POST http://score.local/upload/{{object_id}}/uploads
Authorization: Bearer {{rpt_token}}
Content-Type: application/x-www-form-urlencoded

fileSize={{test_file_size}}
&md5={{test_file_md5}}
&overwrite=true

###
@upload_id = {{initUpload.response.body.uploadId}}
@presigned_url = {{initUpload.response.body.parts.0.url}}

### 7. UPLOAD FILE TO MINIO
# Using hosts file entry: 127.0.0.1 minio (with port-forward to MinIO)
# @name uploadFile
PUT {{presigned_url}}
Content-Type: application/octet-stream

< ./data/{{test_file_name}}

###
@etag_raw = {{uploadFile.response.headers.ETag}}
@etag = {{etag_raw.replace('"', '')}}

# DEBUG: Check what values we have
# object_id: {{object_id}}
# upload_id: {{upload_id}}
# etag: {{etag}}

### 8. TRY RECOVERY (instead of part finalization)
POST http://score.local/upload/{{object_id}}/recovery
Authorization: Bearer {{rpt_token}}
Content-Type: application/x-www-form-urlencoded

fileSize={{test_file_size}}

### A. GET SERVICE ACCOUNT TOKEN for SONG
# @name serviceToken  
POST http://keycloak.local/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{client_id}}
&client_secret={{client_secret}}

###
@service_token = {{serviceToken.response.body.access_token}}

### 9. PUBLISH ANALYSIS (skip complete upload)
PUT http://song.local/studies/{{study_id}}/analysis/publish/{{submitted_analysis_id}}?ignoreUndefinedMd5=true
Authorization: Bearer {{rpt_token}}