replicaCount: 1

fullnameOverride: "score"

url:
  hostname: "score-ilifu.openup.org.za"

image:
  repository: ghcr.io/overture-stack/score-server
  pullPolicy: IfNotPresent
  tag: "5.12.0"

nameOverride: ""

service:
  type: ClusterIP
  port: 8087

score:
  # Spring Configuration
  spring:
    profiles:
      active: "s3,prod,secure"
  
  # Server Configuration
  server:
    port: 8087
    ssl:
      enabled: false
  
  # Song Variables 
  metadata:
    url: "http://song:8080"
    ssl:
      enabled: false
  
  # Client credentials for Score to authenticate to SONG
  clientCredentials:
    id: "dms"
    secret: "dms-secret"
    tokenUrl: "http://keycloak:8080/realms/agari/protocol/openid-connect/token"
    systemScope: "song.READ"
  
  s3:
    endpoint: "http://minio:9000"
    accesskey: "admin"
    secretkey: "admin123"
    sigv4enabled: true
    secured: false
  
  object:
    sentinel: "heliograph"
  
  bucket:
    name:
      object: "object"
      state: "state"
  
  upload:
    partsize: "1073741824"
    connection:
      timeout: "1200000"
  
  auth:
    server:
      provider: "keycloak"
      clientId: "dms"
      clientSecret: "dms-secret" 
      tokenName: "apiKey"
      keycloak:
        host: "http://keycloak:8080"
        realm: "agari"
      scope:
        download:
          study:
            prefix: "study"
            suffix: ".READ"
          system: "score.READ"
        upload:
          study:
            prefix: "study"
            suffix: ".WRITE"
          system: "score.WRITE"
      url: "http://keycloak:8080/realms/agari/apikey/check_api_key/"
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: "http://keycloak:8080/realms/agari/protocol/openid-connect/certs"
          issuerUri: "http://keycloak-ilifu.openup.org.za/realms/agari"

ingress:
  enabled: true
  className: "private"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: score-ilifu.openup.org.za
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi


nodeSelector: {}
tolerations: []
affinity: {}
