apiVersion: v2
name: kafka
description: Apache Kafka cluster using Strimzi operator
type: application
version: 0.1.0
appVersion: "3.6.0"

dependencies:
  - name: strimzi-kafka-operator
    version: 0.39.0
    repository: https://strimzi.io/charts/