# Strimzi Kafka configuration
# This replaces the Bitnami Kafka chart with Strimzi operator

# Kafka cluster configuration
kafka:
  replicas: 1
  
  # Configuration for Kafka brokers
  config:
    # Replication factors for internal topics
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    transactionStateLogMinIsr: 1
    defaultReplicationFactor: 1
    minInsyncReplicas: 1
  
  # Storage configuration
  storage:
    persistent: false  # Set to false for development, true for production
    size: 10Gi
    # storageClass: ""  # Uncomment and specify if needed
  
  # Resource limits
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Zookeeper configuration
zookeeper:
  replicas: 1
  
  # Storage configuration
  storage:
    persistent: false  # Set to false for development, true for production
    size: 5Gi
    # storageClass: ""  # Uncomment and specify if needed
  
  # Resource limits
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

# Override default names if needed
nameOverride: ""
fullnameOverride: "kafka"

# Strimzi operator will be installed as dependency
strimzi-kafka-operator:
  # Enable the operator installation
  enabled: true