replicaCount: 1

fullnameOverride: "kafka"

url:
  hostname: "kafka.local"

# Use Bitnami image instead of Confluent
image:
  repository: bitnami/kafka
  pullPolicy: IfNotPresent
  tag: "3.4.1"

nameOverride: ""

service:
  type: ClusterIP
  port: 9092
  externalPort: 29092

# Enable Zookeeper
zookeeper:
  enabled: true

# Bitnami Kafka configuration
kafka:
  brokerId: 1
  zookeeperConnect: "zookeeper:2181"
  
  # Simple listeners for internal cluster communication
  listenerSecurityProtocolMap: "PLAINTEXT:PLAINTEXT"
  advertisedListeners: "PLAINTEXT://kafka:9092"
  
  # Topic Configuration
  offsetsTopicReplicationFactor: 1
  groupInitialRebalanceDelayMs: 0
  
  # Performance Tuning
  messageMaxBytes: "5242880"
  replicaFetchMaxBytes: "5242880"

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Disable persistence for now
persistence:
  enabled: false

# Security context for Bitnami
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  enabled: true
  image:
    repository: wurstmeister/zookeeper
    tag: latest
  service:
    port: 2181

kafka:
  brokerId: 1
  zookeeperConnect: "zookeeper:2181"
  
  # Listeners (Zookeeper mode)
  listenerSecurityProtocolMap: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  advertisedListeners: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"
  
  # Storage Configuration
  logDirs: "/kafka/kafka-logs"
  logRetentionHours: 168
  logRetentionBytes: -1
  
  # Topic Configuration
  offsetsTopicReplicationFactor: 1
  groupInitialRebalanceDelayMs: 0
  
  # Performance Tuning
  messageMaxBytes: 5242880
  replicaFetchMaxBytes: 5242880

# Persistence
persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: ""

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Pod security context
podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

# Service account
serviceAccount:
  create: false
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Ingress
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: kafka.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
