replicaCount: 1

url:
  hostname: "arranger.local"

image:
  repository: ghcr.io/overture-stack/arranger-ui
  pullPolicy: IfNotPresent
  tag: "3.0.0"

nameOverride: ""
fullnameOverride: "arranger"

service:
  type: ClusterIP
  port: 3000

arranger:
  enableLogs: false
  
  elasticsearch:
    host: "http://elasticsearch:9200"
    user: "elastic"  
    password: "myelasticpassword"
  
  stage:
    baseUrl: "http://arranger.local:3000"
    adminRoot: "http://arranger-server:5050/graphql"

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: arranger.local
      paths:
        - path: /
          pathType: Prefix

probes:
  liveness:
    enabled: false 
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}
