apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (printf "%s-score" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "score" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "score" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
