apiVersion: v2
name: elasticsearch
description: A Helm chart for OpenSearch - Open source search and analytics engine (Elasticsearch replacement)
type: application
version: 0.1.0
appVersion: "2.11.1"
