apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (printf "%s-minio" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "minio" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.consolePort }}
      targetPort: console
      protocol: TCP
      name: console
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "minio" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
