-- Agari Folio v1 Consolidated Schema

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Job status enum
CREATE TYPE job_status AS ENUM ('pending', 'in_progress', 'done', 'failed');

-- =====================
-- Table: pathogens
-- =====================
CREATE TABLE IF NOT EXISTS pathogens (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL UNIQUE,
    scientific_name VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    schema_id UUID
);

-- =====================
-- Table: organisations
-- =====================
CREATE TABLE IF NOT EXISTS organisations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL UNIQUE,
    abbreviation VARCHAR(50),
    url VARCHAR(255),
    about TEXT,
    sharing_policy VARCHAR(20) DEFAULT 'private' CHECK (sharing_policy IN ('public', 'private', 'semi-private')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

-- =====================
-- Table: projects
-- =====================
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    organisation_id VARCHAR(255) NOT NULL DEFAULT 'default-org',
    user_id VARCHAR(255) NOT NULL,
    pathogen_id UUID REFERENCES pathogens(id),
    privacy VARCHAR(20) DEFAULT 'public' CHECK (privacy IN ('public', 'private', 'semi-private')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

-- =====================
-- Table: schemas
-- =====================
CREATE TABLE IF NOT EXISTS schemas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pathogen_id UUID NOT NULL REFERENCES pathogens(id),
    name VARCHAR(255) NOT NULL,
    version INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schema JSONB NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- =====================
-- Table: studies
-- =====================
CREATE TABLE IF NOT EXISTS studies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    study_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    privacy VARCHAR(20) DEFAULT 'public' CHECK (privacy IN ('public', 'private', 'semi-private')),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL
);

-- =====================
-- Table: submissions
-- =====================
CREATE TABLE IF NOT EXISTS submissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    submission_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50) DEFAULT 'draft',
    error JSONB,
    user_id UUID
);

-- =====================
-- Table: isolates
-- =====================
CREATE TABLE IF NOT EXISTS isolates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    object_id UUID,
    isolate_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE NULL,
    tsv_row INTEGER,
    error JSONB,
    status VARCHAR(50),
    seq_error JSONB,
    isolate_id VARCHAR(255)
);

-- =====================
-- Table: submission_files
-- =====================
CREATE TABLE IF NOT EXISTS submission_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id UUID NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    isolate_id UUID,
    filename VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL CHECK (file_type IN ('tsv', 'fasta')),
    object_id UUID,
    file_size BIGINT,
    md5_hash VARCHAR(32),
    is_split BOOLEAN DEFAULT false,
    parent_file_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- =====================
-- Table: jobs
-- =====================
CREATE TABLE IF NOT EXISTS jobs (
    id SERIAL PRIMARY KEY,
    status job_status NOT NULL DEFAULT 'pending',
    payload JSONB,
    retry_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT now()
);

-- =====================
-- Table: logs
-- =====================
CREATE TABLE IF NOT EXISTS logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    log_type VARCHAR(50) NOT NULL,
    resource_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    log_entry TEXT
);

-- =====================
-- Indexes
-- =====================
CREATE INDEX IF NOT EXISTS idx_projects_pathogen ON projects(pathogen_id);
CREATE INDEX IF NOT EXISTS idx_projects_organisation ON projects(organisation_id);
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id);
CREATE INDEX IF NOT EXISTS idx_projects_privacy ON projects(privacy);
CREATE INDEX IF NOT EXISTS idx_studies_project ON studies(project_id);
CREATE INDEX IF NOT EXISTS idx_studies_study_id ON studies(study_id);
CREATE INDEX IF NOT EXISTS idx_pathogens_name ON pathogens(name);
CREATE INDEX IF NOT EXISTS idx_organisations_name ON organisations(name);
CREATE INDEX IF NOT EXISTS idx_logs_log_type ON logs(log_type);
CREATE INDEX IF NOT EXISTS idx_submissions_project ON submissions(project_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions(status);
CREATE INDEX IF NOT EXISTS idx_isolates_submission_id ON isolates(submission_id);
CREATE INDEX IF NOT EXISTS idx_isolates_object_id ON isolates(object_id);
CREATE INDEX IF NOT EXISTS idx_isolates_data_gin ON isolates USING GIN (isolate_data);
CREATE INDEX IF NOT EXISTS idx_jobs_pending ON jobs(status, created_at) WHERE status = 'pending';

-- =====================
-- Triggers and Functions
-- =====================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_isolates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_pathogens_updated_at 
    BEFORE UPDATE ON pathogens 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_projects_updated_at 
    BEFORE UPDATE ON projects 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_studies_updated_at 
    BEFORE UPDATE ON studies 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_organisations_updated_at 
    BEFORE UPDATE ON organisations 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_isolates_updated_at
    BEFORE UPDATE ON isolates
    FOR EACH ROW EXECUTE FUNCTION update_isolates_updated_at();

-- =====================
-- Foreign Keys
-- =====================
ALTER TABLE pathogens ADD CONSTRAINT fk_pathogen_schema FOREIGN KEY (schema_id) REFERENCES schemas(id);
ALTER TABLE schemas ADD CONSTRAINT schemas_pathogen_id_fkey FOREIGN KEY (pathogen_id) REFERENCES pathogens(id);
ALTER TABLE studies ADD CONSTRAINT studies_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE submission_files ADD CONSTRAINT submission_files_isolate_id_fkey FOREIGN KEY (isolate_id) REFERENCES isolates(id) ON DELETE SET NULL;
ALTER TABLE submission_files ADD CONSTRAINT submission_files_parent_file_id_fkey FOREIGN KEY (parent_file_id) REFERENCES submission_files(id);
ALTER TABLE submission_files ADD CONSTRAINT submission_files_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE CASCADE;
ALTER TABLE submissions ADD CONSTRAINT submissions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

-- =====================
-- Views
-- =====================
CREATE OR REPLACE VIEW project_details AS
SELECT 
    p.id,
    p.name,
    p.description,
    p.organisation_id,
    p.user_id,
    p.privacy,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    pat.name as pathogen_name,
    pat.scientific_name as pathogen_scientific_name,
    COUNT(s.id) as study_count
FROM projects p
LEFT JOIN pathogens pat ON p.pathogen_id = pat.id AND pat.deleted_at IS NULL
LEFT JOIN studies s ON p.id = s.project_id AND s.deleted_at IS NULL
WHERE p.deleted_at IS NULL
GROUP BY p.id, p.name, p.description, p.organisation_id, 
         p.user_id, p.privacy, p.created_at, p.updated_at, p.deleted_at,
         pat.name, pat.scientific_name;

CREATE OR REPLACE VIEW study_details AS
SELECT 
    s.id,
    s.study_id,
    s.name,
    s.description,
    s.status,
    s.privacy,
    s.project_id,
    s.created_at,
    s.updated_at,
    s.deleted_at,
    p.name as project_name,
    pat.name as pathogen_name
FROM studies s
JOIN projects p ON s.project_id = p.id AND p.deleted_at IS NULL
LEFT JOIN pathogens pat ON p.pathogen_id = pat.id AND pat.deleted_at IS NULL
WHERE s.deleted_at IS NULL;

CREATE VIEW organisation_projects AS
SELECT 
    o.id as organisation_id,
    o.name as organisation_name,
    COUNT(p.id) as project_count
FROM organisations o
LEFT JOIN projects p ON o.id = p.organisation_id AND p.deleted_at IS NULL
WHERE o.deleted_at IS NULL
GROUP BY o.id, o.name;

-- =====================
-- Comments
-- =====================
COMMENT ON TABLE pathogens IS 'Reference table for pathogen information';
COMMENT ON TABLE projects IS 'Main projects table containing project metadata';
COMMENT ON TABLE studies IS 'Studies table containing study information linked to projects';
COMMENT ON VIEW project_details IS 'Denormalized view of projects with pathogen and study count information';
COMMENT ON VIEW study_details IS 'Denormalized view of studies with project and pathogen information';
COMMENT ON TABLE organisations IS 'Table containing organisation information';
COMMENT ON TABLE logs IS 'Log table for tracking user actions';
COMMENT ON TABLE submissions IS 'Table for tracking data submissions related to projects';
COMMENT ON TABLE jobs IS 'Basic job queue - starting simple';
COMMENT ON TABLE isolates IS 'Stores individual isolate data linked to submissions and FASTA files';
COMMENT ON TABLE submission_files IS 'Tracks uploaded files associated with submissions and isolates';
COMMENT ON COLUMN submission_files.filename IS 'Original filename of the uploaded file';
COMMENT ON COLUMN submission_files.file_type IS 'Type of file (tsv or fasta)';
COMMENT ON COLUMN submission_files.object_id IS 'UUID reference to the file object in MinIO storage';
COMMENT ON COLUMN submission_files.file_size IS 'Size of the file in bytes';
COMMENT ON COLUMN submission_files.md5_hash IS 'MD5 hash of the file content for integrity checking';
COMMENT ON COLUMN submission_files.is_split IS 'Whether this file was created by splitting a larger file';
COMMENT ON COLUMN submission_files.parent_file_id IS 'Reference to the original file if this is a split file';
COMMENT ON COLUMN isolates.isolate_data IS 'JSONB column containing isolate metadata and analysis data';
COMMENT ON COLUMN isolates.object_id IS 'UUID reference to the FASTA file object in MinIO storage';
COMMENT ON COLUMN isolates.submission_id IS 'Foreign key to submissions table';
COMMENT ON COLUMN isolates.id IS 'Primary key UUID';
