apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  kafka:
    version: 3.6.0
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: {{ .Values.kafka.config.offsetsTopicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.transactionStateLogReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.transactionStateLogMinIsr }}
      default.replication.factor: {{ .Values.kafka.config.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.kafka.config.minInsyncReplicas }}
      inter.broker.protocol.version: "3.6"
    storage:
      {{- if .Values.kafka.storage.persistent }}
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      {{- if .Values.kafka.storage.storageClass }}
      class: {{ .Values.kafka.storage.storageClass }}
      {{- end }}
      {{- else }}
      type: ephemeral
      {{- end }}
    resources:
      {{- toYaml .Values.kafka.resources | nindent 6 }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      {{- if .Values.zookeeper.storage.persistent }}
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      {{- if .Values.zookeeper.storage.storageClass }}
      class: {{ .Values.zookeeper.storage.storageClass }}
      {{- end }}
      {{- else }}
      type: ephemeral
      {{- end }}
    resources:
      {{- toYaml .Values.zookeeper.resources | nindent 6 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}