apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default (printf "%s-kafka" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "kafka" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: {{ .Values.service.externalPort }}
      targetPort: external
      protocol: TCP
      name: external
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "kafka" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
