apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    strimzi.io/cluster: {{ include "kafka.fullname" . }}
    strimzi.io/kind: Kafka
    strimzi.io/name: {{ include "kafka.fullname" . }}-kafka