apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "folio.fullname" . }}
  labels:
    {{- include "folio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "folio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "folio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            # Keycloak authentication configuration
            - name: KEYCLOAK_HOST
              value: {{ .Values.folio.auth.keycloak.host | quote }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.folio.auth.keycloak.realm | quote }}
            - name: KEYCLOAK_ISSUER
              value: {{ .Values.folio.auth.keycloak.issuer | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.folio.auth.keycloak.clientId | quote }}
            - name: KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.folio.auth.keycloak.clientSecret | quote }}
            - name: DB_HOST
              value: {{ .Values.folio.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.folio.database.port | quote }}
            - name: DB_NAME
              value: {{ .Values.folio.database.name | quote }}
            - name: DB_USER
              value: {{ .Values.folio.database.user | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.folio.database.password | quote }}
            - name: OVERTURE_SCORE
              value: {{ .Values.folio.overture.score | quote }}
            - name: OVERTURE_SONG
              value: {{ .Values.folio.overture.song | quote }}
          livenessProbe:
            httpGet:
              path: /info/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /info/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
